name: Test Action

on:
  release:
    types: [ published ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./
        id: version-bump
        with:
          github-token: ${{ secrets.github_token }}
          bump: prepatch
          prerelease-text: dev
          build: ${{ github.run_number }}

      - name: Check Version Bumper output
        run: echo ${{ steps.version-bump.outputs.version }}